global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'spark-master'
    metrics_path: '/metrics/master/prometheus/'
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: 'spark-workers'
    metrics_path: '/metrics/worker/prometheus/'
    static_configs:
      - targets: ['spark-worker-1:8081', 'spark-worker-2:8081']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'trino'
    static_configs:
      - targets: ['trino:8088']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']
